
name: 'Terraform CI'

on:
  pull_request:
    branches:
      - main
    paths:
      - '**.tf'
      - '**.tfvars'

jobs:
  format:
    name: 'Terraform Format'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4

      - name: 'Set up Terraform'
        uses: hashicorp/setup-terraform@v3

      - name: 'Terraform Fmt Check'
        run: terraform fmt -check -recursive

  security-scan:
    name: 'Checkov Security Scan'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4

      - name: 'Set up Python'
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: 'Run Checkov action'
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: ./
          framework: terraform
          soft_fail: false